### ISSUE TITLE
请问启动报这个错是什么原因呢?

### ISSUE THREAD

**Issue by it-honghui** [izerui/tomcat-redis-session-manager#1]
四月 23, 2019 2:57:35 下午 org.apache.coyote.http11.AbstractHttp11Processor process
严重: Error processing request
java.lang.NullPointerException
	at com.orangefunction.tomcat.redissessions.RedisSessionHandlerValve.invoke(RedisSessionHandlerValve.java:28)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1137)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2575)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2564)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by izerui** [comment]
https://github.com/jcoleman/tomcat-redis-session-manager/blob/master/src/main/java/com/orangefunction/tomcat/redissessions/RedisSessionHandlerValve.java

应该manager为空，检查啊配置是否正确

**Comment by it-honghui** [comment]
哦,谢谢啊 这个问题已经解决了,原因是我把配置写到server.xml里了,应该是放在context.xml里,然后还有个问题就是,我再ssm框架上这个session共享实现成功了,但是我们项目用的jdk7,tomcat7,struts2,而且spring版本是2.5.6比较低,,然后没有报错,也没有效果,redis也没有插入session数据,不知道是不兼容还是怎么回事,jedis版本也换低的试了,没有效果

**Comment by izerui** [comment]
只要tomcat session能基于redis共享成功，其他依赖tomcat管理session的应用基本上都可以。不关心应用的框架的。
保证下面两条必要因素就可以
1. tomcat 配置session 交由redis
2. 应用的session管理交由tomcat管理，如果应用针对session做了个性化管理，session 共享会失效。

**Comment by it-honghui** [comment]
非常感谢,问题解决了,果然是项目里有其他配置对session坐了个性化管理,去掉那个就好了

**Comment by izerui** [comment]
不客气
